### ISSUE TITLE
greeter screen star animation

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-session-ui#1]
The new version of the greeter screen misses the cool star animation.
Would it be possible to re-integrate that?

**Comment by fasheng** [comment]
I guess it will come back later ;)

**Comment by manateelazycat** [comment]
Because deepin should support mips/alpha, those chips very slow for cool star animiation.
We have remove those animation from new version.

Very sorry for that.
We pherphas add those animation until mips/alpha chips have enough performance.
