### ISSUE TITLE
Overlapped lightdm-greeter in Antergos

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-session-ui#11]
I haven't problem when i begins my session; but after suspend and re-enter in my session, i have to begin session in the `Antergos` `lightdm-greeter`, normal behaviour, and after it again begin session in `deepin` desktop.

But is a fake, his `lightdm-greeter` is overlapped with the desktop, because the password field doesn't works fine, i text many things but anything happen, or i believed it; i click in the suspension button and after cancel it and i can now put my password in the greeter; after enter in the desktop i can see that all things that i text was in gedit, in the program that i was working before to suspend the session.

Which is the error?

__UPDATE:__
I could prove that this problem also happen with `deepin` greeter: i change the `Antergos` default greeter by `deepin` greeter; today after re-init the session, susspended before, i had to begin session in the greeter, as if i am beginning session, and after again in the `screensaver` greeter ( that have my custom wallpaper, ironically).

Why happen this??

**Comment by hualet** [comment]
@SalahAdDin do you still get this problem?

**Comment by SalahAdDin** [comment]
No, not until now, but i still have the problem with `disk` plugin icon.

@hualet Thank you!
