### ISSUE TITLE
[ARCH] Volume control icon not working on lockscreen

### ISSUE THREAD

**Issue by jhenrique09** [linuxdeepin/dde-session-ui#135]
Not possible to mute or control music volume at all.
![Captura de Tela_20190704142442](https://user-images.githubusercontent.com/22119113/60682005-dabab500-9e67-11e9-946e-44a3ad1355da.png)

**Comment by jhenrique09** [comment]
Somehow dbus is returning '0' at volume

dbus-monitor output:

method call time=1562262274.181582 sender=:1.45 -> destination=org.mpris.MediaPlayer2.spotify serial=448 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.mpris.MediaPlayer2.Player"
   string "Volume"
method return time=1562262274.181974 sender=:1.111 -> destination=:1.45 serial=279 reply_serial=448
   variant       double 0

**Comment by BLumia** [comment]
Thanks for reporting this issue, could you test if close spotify and using deepin-music for music playback also have this issue? Thanks.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
