### ISSUE TITLE
Onboard parameter in virtualkbinstance.cpp

### ISSUE THREAD

**Issue by mas-ony** [linuxdeepin/dde-session-ui#144]
Please make onboard parameter configurable.

**Comment by BLumia** [comment]
Since the design principle is provide as less configs as we can to avoid confusion of users. Could you specific which parameters need to be configurable and why? Thanks.

**Comment by masony** [comment]
In other distro which use lightdm-gtk-greeter.conf, I can use this config to change onboard appearance:

**[greeter]
keyboard=onboard --theme=Droid**


dde-session-ui file virtualkbinstance.cpp line 46
**p->start("onboard", QStringList() << "-e" << "--layout" << "Small");**

Which show onboard using default theme and Small layout, which is not proportional in my tablet.

Hope you understand what i meant. Thanks.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
