### ISSUE TITLE
Unreadable MPRIS string on dde-lock

### ISSUE THREAD

**Issue by bloomvdomino** [linuxdeepin/dde-session-ui#151]
On dde-lock, the MPRIS string is black, while the buttons are white. That makes the string unreadable!

![DeepinBildschirmfoto_20190809225708](https://user-images.githubusercontent.com/33204710/62809926-a4262900-bafc-11e9-9a3d-8c4ea9b879c3.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
