### ISSUE TITLE
dde-lock vulnerability, interaction with the screen-locked system

### ISSUE THREAD

**Issue by sha0coder** [linuxdeepin/dde-session-ui#155]
Hello, it is possible to interact with the screen-locked system under certain situations.
The apps can map some keys that can be trigeered even with the screen locked. 
For example in the case of a VirtualBox, with the screen-locked you can press [Ctrl] key to set the focus on the VM then all the keys are sent to the VM. 
I managed to open a CMD and a calculator, with the screen locked. But this is not just a problem with VM's, the app-level key binding are still enabled when the screen is locked.

regards.

**Comment by BLumia** [comment]
cc @hualet

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
