### ISSUE TITLE
Critical security breach in dde-lock

### ISSUE THREAD

**Issue by ArthurKnoep** [linuxdeepin/dde-session-ui#16]
Hello,

On dde-lock :

When we type lot of characters in the password bar (More than 5 giga characters) and when we press "Enter" after, dde-lock crash which have for consequence to unlock the laptop.

My system :

arthur@arthur-pc
OS: Deepin 15.4 unstable
Kernel: x86_64 Linux 4.9.0-deepin5-amd64
Uptime: 5h 10m
Packages: 
Shell: bash 4.4.11
Resolution: 1920x1080
WM: Mutter(DeepinGala)
WM Theme: Ambiance
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
CPU: Intel Core i7-6500U CPU @ 2.5GHz
GPU: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
RAM: 5621MiB / 7868MiB

**Comment by felixonmars** [comment]
@hualet

**Comment by ArthurKnoep** [comment]
In fact, I dunno if the bug is always present

I can't reproduce it but I dunno if it is solved

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
