### ISSUE TITLE
Mouse problem on dde-wm-chooser Virtualbox - Deepin 15.4.1

### ISSUE THREAD

**Issue by andeon** [linuxdeepin/dde-session-ui#19]
The Mouse works fine on login screen, but after the logon when dde-wm-chooser is open its not works anymore, so the user stays stuck on the screen. Maybe if the keyboard has enabled to choose these options it could be a good idea.

**Comment by oberon2007** [comment]
@andeon do you have the latest version of **startdde** (3.1.13) installed?

**Comment by andeon** [comment]
@oberon2007 I'm check this with `apt-cache policy startdde` and show me **Installed: 3.1.11-1**

I'm update the system add in /etc/apt/sources.list `deb http://proposed.packages.deepin.com/deepin panda main contrib non-free ` and after this run `sudo apt update && sudo apt upgrade`. 

Now, the system detects that I'm using a VM and ask to choose between two modes after the login screen, as the mouse not works, I'm just remove the dde-wm-chooser from /usr/bin to avoid these options for continue testing and using the system.

**Comment by andeon** [comment]
@oberon2007 Apparentely de problem with the cursor mouse stuck in **dde-wm-chooser** is the **dde-welcome**  if I remove this file  from /usr/lib/deepin-daemon/ the cursor works normally. 

Not sure if the devs fixed it, but I can see a recent commit on the folder https://github.com/linuxdeepin/dde-session-ui/tree/master/dde-welcome

**Comment by andeon** [comment]
The release update in 21/07/2017 fixed the issue!
