### ISSUE TITLE
logo greeter screen

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-session-ui#2]
For Manjaro-Deepin I would like to customize the logo on the greeter screen.
Since the greeter has been built into deepin-session-ui I have not been able to find the source of the that logo to replace.
I have tried [this](https://github.com/oberon2007/deepin-session-ui-manjaro/commit/068c40ae7f4db7062c404bad468e56dcfe412fde) with no success. Also replacing the logo [here](https://github.com/oberon2007/deepin-session-ui-manjaro/commit/5c529983959ea57b30c2fe46777567dbc7534a33) was not effective.
Could you kindly point me to the right place in the source?
Thank you :)

**Comment by pangpangpang3** [comment]
We have a backup image of the logo, we will change our settings in order to meet your demand, we will release new versions  in a week!

Thanks for your reply!

**Comment by oberon2007** [comment]
Sounds great! Thank you very much for your kind help! :-)
I'm afraid I don't know what you mean with "backup image" or where this is currently located but in any case I'll be happy to find out about your modifications.
I think it will be great to provide this fantastic DE in a customizable form to make it globally attractive.

**Comment by oberon2007** [comment]
Thank you very much, it seems to be working fine now :)

**Comment by pangpangpang3** [comment]
Glade to hear that!　:)
