### ISSUE TITLE
blackscreen since update

### ISSUE THREAD

**Issue by jaidmin** [linuxdeepin/dde-session-ui#21]
I'm running deepin on arch

since recently lightdm-deepin-greeter leads to a blackscreen
when I change the lightdm greeter in /etc/lightdm/lightdm.conf to another greeter (gtk for example) everything works.
When the system is booted and I run "lightdm-deepin-greeter" the greeter shows, the desktop file is also there in /usr/share/xgreeters

the blackscreen cannot be escaped by win+alt+f2 or any other f-key, if you tell me how I can collect further logs after a reboot, that would be very helpful

this seems somewhat similar to https://github.com/linuxdeepin/dde-session-ui/issues/8 so I am optimisitic that a future update will fix everything

**Comment by michaelcyyuen** [comment]
Oh i have same problem too, ubuntu 17.10, got black screen after login.

**Comment by jouyouyun** [comment]
@kirigayakazushin

**Comment by felixonmars** [comment]
Is it still the case with the latest 4.3.0 release?

**Comment by Maxung** [comment]
@felixonmars for me yes

**Comment by Swizz** [comment]
Did you solve this issue ? 
I am encountering this on a fresh install.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
