### ISSUE TITLE
Login, shutdown and launcher screen no longer blur background

### ISSUE THREAD

**Issue by Skillzore** [linuxdeepin/dde-session-ui#25]
My background no longer gets blur when I am at the login screen, the shutdown screen or in the launcher screen.
https://imgur.com/sLeMX0y - login screen
https://imgur.com/GCLBgC4 - shutdown screen
https://imgur.com/lytV5Mj - launcher screen

I am running Arch with latest kernel. All packages are up to date and have even tried reinstalling all the deepin packages, to no avail.

What do you need from me to diagnose this issue?

**Comment by jouyouyun** [comment]
@electricface

**Comment by hualet** [comment]
https://github.com/linuxdeepin/dde-session-ui/issues/26

**Comment by SalahAdDin** [comment]
I have the same problem now.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
