### ISSUE TITLE
dde-shutdown shows only white background

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/dde-session-ui#26]
Any time I toggle shutdown botton, it only shows a white background. I doult that [this commit](https://github.com/linuxdeepin/dde-session-ui/commit/d1f8809c0ed85956ce79c963f0ddf1cdf64baff2) is not working.

dde-session-ui version: 4.1.7
Qt version: 5.9.3

**Comment by jouyouyun** [comment]
@kirigayakazushin

**Comment by kirigayakazushin** [comment]
please set current wallpaper again. [this commit](https://github.com/linuxdeepin/dde-session-ui/commit/d1f8809c0ed85956ce79c963f0ddf1cdf64baff2) It is fixed that a white interface will be seen at boot time。

**Comment by zhtengw** [comment]
@kirigayakazushin <https://github.com/kirigayakazushin>, It does not take effect. No matter how many times I changed the wallpaper for only lockscreen or for both, the background of dde-shutdown keeps to be white.

Best Regards,
Aten Zhang

**Comment by hualet** [comment]
version of dde-daemon ?

**Comment by zhtengw** [comment]
That is dde-daemon-3.2.7.
And all components of DDE are the latest version in github.

Best Regards,
Aten Zhang

**Comment by zhtengw** [comment]
Fixed when updated to version 4.2.0.

**Comment by mbhtkd** [comment]
I solved it just by changing the wallpaper
