### ISSUE TITLE
lightdm-deepin-greater constantly consumes 6-10% of one core

### ISSUE THREAD

**Issue by andrew-grechkin** [linuxdeepin/dde-session-ui#27]
After reboot, when nobody is logged in with lightdm-deepin-greater it constantly doing something and consuming 6-10% of one core.

How to see:
Connect to the machine with SSH or login to the system using text interface (pressing Ctrl-Alt-F2)
run htop and check cpu resources for lightdm-deepin-greater

**Comment by felixonmars** [comment]
Is it still the case with the latest 4.3.0 release? IIRC it was a huge rewrite.

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/766

This issue has reported the issue and submitted a fix, only 0.7% cpu on my device.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
