### ISSUE TITLE
Widgets missing

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/dde-session-ui#28]
On login screen the input field is hidden,
on shutdown/restart/... screen all the buttons are hidden.

The hidden widgets can be used if you know, where to click blindly, but it is a real bad feature.

Using Arch.

**Comment by oberon2007** [comment]
Looks like from just isn't ready for latest qt5.10
See [here](https://github.com/linuxdeepin/developer-center/issues/476).

**Comment by DasJott** [comment]
This issue seems to be fixed noew. At least on my machine.
Can anybody confirm this?

**Comment by DasJott** [comment]
Saw the other report... it's fixed.
