### ISSUE TITLE
Asks twice for password

### ISSUE THREAD

**Issue by bolognese** [linuxdeepin/dde-session-ui#29]
When both `Password required to wake up the monitor` and `Password required to wake up the computer` are checked, the lock screen is called twice.

**Comment by jouyouyun** [comment]
Once for blackscreen? Once for suspend? @electricface

**Comment by bolognese** [comment]
Yes.
The first time, everything works as expected but one or two seconds later, you're asked again for the password.

**Comment by michalzubkowicz** [comment]
I can still confirm this issue.

**Comment by michalzubkowicz** [comment]
Try newest Deepin 15.6, it's not asking now in my case

**Comment by jouyouyun** [comment]
........
