### ISSUE TITLE
Auto-login fails from time to time

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-session-ui#31]
HOW TO REPRODUCE:
From time to time auto-login fails. They you are presented with the greeter screen.
There the user has a button to start the session. That button also doesn't work.

SYSTEM SPECS:
- Deepin Session UI 4.3.7.1
- Manjaro Linux Stable

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
