### ISSUE TITLE
Lockscreen allows to view content of computer

### ISSUE THREAD

**Issue by michalzubkowicz** [linuxdeepin/dde-session-ui#32]
Deepin lockscreen allows users to view content and move windows etc for a few seconds after resuming from suspend. 
It happens especially with two monitors connected. I'm using newest Deepin.

**Comment by SalahAdDin** [comment]
@michalzubkowicz it happens right now with the last update in `Antergos` after any suspension.

**Comment by michalzubkowicz** [comment]
I think it's fixed in newest Deepin 15.6

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
