### ISSUE TITLE
After upgrade to deepin-session-ui 4.4.4, login and logout screen are unreadable.

### ISSUE THREAD

**Issue by FredBezies** [linuxdeepin/dde-session-ui#33]
Hello.

I noticed this bug on both Archlinux and Manjaro with Deepin desktop environment installed.

When I upgraded to Deepin-session-ui-4.4.4 (or later ?), both login and logout screens are unreadable. Downgrading to 4.4.3 fixes this issue.

Here is a screenshot of login screen with displaying bug:

![deepin-session-4 4 5](https://user-images.githubusercontent.com/8571419/41505676-5f461da0-720e-11e8-9595-75a9ea1c42cd.png)

Annoying. What breaks greeter display in deepin-session-ui 4.4.4?

**Comment by sgse** [comment]
New path to wallpaper jpg.


![deepinbildschirmfoto_bereich auswahlen_20180617093342](https://user-images.githubusercontent.com/17575778/41505863-1d3b7abe-7212-11e8-8c30-29021b5b7116.png)

**Comment by MrMyrmex** [comment]
I've have the exact same issue.

**Comment by jouyouyun** [comment]
Change the background in Desktop.

**Comment by sgse** [comment]
I'd rather trade my wife than the wallpaper ;-)

**Comment by squirz96** [comment]
Has anyone of you solved the issue?

**Comment by felixonmars** [comment]
I believe this has already been fixed in latest packages.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
