### ISSUE TITLE
Cannot overlap windows in half-screen

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-session-ui#34]
I have two windows occupying the half-screen each one. After that, I want to put another new window in, for example, left side, overlapping the existing one, and I got this:
![deepin-screen-recorder_select area_20180717102558](https://user-images.githubusercontent.com/5034215/42802764-83cb1292-89ac-11e8-946e-4a93f6f36b79.gif)

Why? Is it normal?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Comment by SalahAdDin** [comment]
It is fixed by the way!
