### ISSUE TITLE
Failed to activate service 'com.deepin.dde.Welcome'

### ISSUE THREAD

**Issue by arisskz6** [linuxdeepin/dde-session-ui#35]
Today I got a bunch of deepin package updates, seems almost all of the deepin applications got updates. After installing I rebooted, but something weird happened.
**The Welcome  sound run out but the mouse loop continues a long time, maybe  3 minutes.**
Here's the log

```
Jul 21 16:01:18 arch dbus-daemon[2282]: [session uid=1000 pid=2282] Failed to activate service 'com.deepin.dde.Welcome': timed out (service_start_timeout=120000ms)
Jul 21 16:01:18 arch startdde[2277]: main.go:117: Failed to exit welcome: org.freedesktop.DBus.Error.TimedOut:Failed to activate service 'com.deepin.dde.Welcome': timed out (service_start_timeout=120000ms)
```
environment: DDE on archlinux

**Comment by Urgau** [comment]
Same problem, but it seems to be solve with the last update.
