### ISSUE TITLE
Keyboard layout changes after unlocking

### ISSUE THREAD

**Issue by tpbarboza** [linuxdeepin/dde-session-ui#36]
After I unlock session, the keyboard layout is changed to wrong model.
The correct setting for my keyboard is set by:
setxkbmap -model thinkpad -layout br

From journalctl after unlocking screen I get the following:

    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.322 [Debug ] [lockframe.cpp LockFrame::LockFrame 38] LockFrame geometry: QRect(0,0 640x480)
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.371 [Debug ] [userwidget.cpp UserWidget::onLoginUserListChanged 277] Logind Uid List: (1000)
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.372 [Debug ] [userwidget.cpp UserWidget::onLoginUserListChanged 286] "Update tiago login state: 1"
    ago 16 12:09:50 tp dbus-daemon[1019]: [session uid=1000 pid=1019] Successfully activated service 'com.deepin.dde.lockFront'
    ago 16 12:09:50 tp dbus-daemon[541]: [system] Activating service name='com.deepin.dde.LockService' requested by ':1.3979' (uid=1000 pid=30954 comm="/usr/bin/dde-lock ") (using servicehelper)
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.494 [Debug ] [kblayoutwidget.cpp KbLayoutWidget::setListItemChecked 159] m_layoutbuttons.length: 2 0
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.495 [Debug ] [kblayoutwidget.cpp KbLayoutWidget::setListItemChecked 162] itemIndex itemText: 0 "Portuguese (Brazil, IBM/Lenovo ThinkPad)"
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.495 [Debug ] [kblayoutwidget.cpp KbLayoutWidget::setButtonsChecked 139] XsetButtonsChecked: "Portuguese (Brazil, IBM/Lenovo ThinkPad)"
    ago 16 12:09:50 tp dbus-daemon[541]: [system] Successfully activated service 'com.deepin.dde.LockService'
    ago 16 12:09:50 tp com.deepin.dde.LockService[541]: manager.go:225: Echo off: Password:
    ago 16 12:09:50 tp com.deepin.dde.LockService[541]: manager.go:240: Join select: 30954tiago
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.555 [Debug ] [kblayoutwidget.cpp KbLayoutWidget::setButtonsChecked 153] 0 "" "setxkbmap -layout br"
    ago 16 12:09:50 tp org.freedesktop.Notifications[1019]: 2018-08-16, 12:09:50.559 [Debug ] [ 0] setBasePosition 1366 0 QRect(0,0 0x0)
    ago 16 12:09:50 tp org.freedesktop.Notifications[1019]: 2018-08-16, 12:09:50.560 [Debug ] [ 0] setBasePosition 1366 0 QRect(0,0 0x0)
    ago 16 12:09:50 tp org.freedesktop.Notifications[1019]: 2018-08-16, 12:09:50.563 [Debug ] [ 0] setBasePosition 1366 0 QRect(0,0 0x0)
    ago 16 12:09:50 tp org.freedesktop.Notifications[1019]: 2018-08-16, 12:09:50.564 [Debug ] [ 0] setBasePosition 1366 0 QRect(0,0 0x0)
    ago 16 12:09:50 tp com.deepin.dde.LockService[541]: manager.go:164: In authenticating: 30954tiago
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.620 [Debug ] [lockmanager.cpp LockManager::lockServiceEvent 359] 2 30954 "tiago" "Password: "
    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.620 [Debug ] [lockmanager.cpp LockManager::lockServiceEvent 379] prompt secret from pam: "Password: "
    ago 16 12:09:52 tp com.deepin.dde.LockService[541]: manager.go:190: In authenticating: 30954tiago
    ago 16 12:09:52 tp com.deepin.dde.LockService[541]: manager.go:293: Authenticate success
    ago 16 12:09:52 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:52.120 [Debug ] [lockmanager.cpp LockManager::lockServiceEvent 359] 6 30954 "tiago" "Authenticated"

As we can see in this line,

    ago 16 12:09:50 tp com.deepin.dde.lockFront[1019]: 2018-08-16, 12:09:50.555 [Debug  ] [kblayoutwidget.cpp   KbLayoutWidget::setButtonsChecked   153] 0 "" "setxkbmap -layout br"
the keyboard is being reset without the model argument (and probably might be missing the variant as well for other keyboard settings), which is probably the case of the error.

**Comment by haruyukilxz** [comment]
hey, try this deb file.
https://ci.deepin.io/job/dde-session-ui/2068/artifact/dde-session-ui_4.5.1~gerrit+37841~1_amd64.deb

I tried to read the model and reset it so that no information should be lost.

**Comment by tpbarboza** [comment]
Hi mate, 
I'm afraid I'll not be able to test this artifact for you as I'm using only the Deepin DDE over Manjaro (arch based).

**Comment by Saduff** [comment]
Hi, I have the same problem. I have a layout with `nodeadkeys`, but layout is set without the `-variant` option after unlocking:
```
[Debug  ] [kblayoutwidget.cpp   KbLayoutWidget::setListItemChecked  179] itemIndex itemText: 0 "Estonian (no dead keys)"
[Debug  ] [kblayoutwidget.cpp   KbLayoutWidget::setButtonsChecked   141] XsetButtonsChecked: "Estonian (no dead keys)"
[Debug  ] [kblayoutwidget.cpp   KbLayoutWidget::setButtonsChecked   170] 0 "" "setxkbmap" ("-model", "thinkpad", "-layout", "ee")
```

The command executed is: `setxkbmap -model thinkpad -layout ee`, but it should be `setxkbmap -model thinkpad -layout ee  -variant nodeadkeys`

The relevant line of code seems to be:
https://github.com/linuxdeepin/dde-session-ui/blob/c1461978eb66e39e0a6db80257e66dc0bfa48397/widgets/kblayoutwidget.cpp#L168

It never sets a `-variant`, but it's necessary for some layouts, for example `nodeadkeys`, probably some others as well.

**Comment by DeGreedy** [comment]
> Hi, I have the same problem. I have a layout with `nodeadkeys`, but layout is set without the `-variant` option after unlocking:
> 
I think I have the same issue - and I have described it in feedback https://feedback.deepin.org/feedback/detail/29184?token=2NprjrfvyokqLIlG (still no reaction though)

**Comment by Foxei** [comment]
There is now a suitable disskusion to this topic which has even been marked as "严重" which means serious: https://github.com/linuxdeepin/internal-discussion/issues/1992

**Comment by Foxei** [comment]
I've made a pull request for the fix.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
