### ISSUE TITLE
Mate loginscreen and shutdown replacement

### ISSUE THREAD

**Issue by aromero86** [linuxdeepin/dde-session-ui#37]
Hi guys, 

I'm customizing my mate desktop and I'm using some deepin elements.  I have a question: Can I use `dde-session-ui` with **mate desktop**? How can I replace this screens without install full deepin desktop (I need Mate for other reasons)?

Thank you and sorry about my english

**Comment by jouyouyun** [comment]
Set `greeter-session` to `lightdm-deepin-greeter` in the file `/etc/lightdm/lightdm.conf`

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
