### ISSUE TITLE
[Arch][Manjaro] Changing GRUB's background message does not work

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-session-ui#40]
I know there is other issue related about but i could not find it.

I was testing **Deepin** in **Manjaro Deepin 17.2**; i changed the **GRUB** image but it didn't work.

Why? Why GRUB configurator does not work in **ArchLinux** yet?

**Comment by jouyouyun** [comment]
@electricface

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
