### ISSUE TITLE
[Arch][Manjaro]Can't switch user in lightdm

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/dde-session-ui#41]
Hi,
I'm running Manjaro with latest updates (DISTRIB_RELEASE=18.0.0-r)
I have problem with the lightdm-deepin-greeter where it doesn't allow me to change the user if I have multiple users, I can click the switch user icon at the lower right corner but I can't select another user!

**Steps to reproduce:**
1- add a new user, for me I used this command:
`useradd -G users,wheel,video,audio,network,power,wireshark,sys,lp,storage -m -s /bin/zsh -U newuser`
2- restart the lightdm service:
`systemctl restart lightdm`
3-click on the lower right corner icon (switch user icon), two users will appear and you can use the mouse or keyboard to select one of them, but the choice is not saved, as soon as you choose a user you will get back to the password screen and you will find that lightdm chose a different user for you

Regards

**Comment by jouyouyun** [comment]
@haruyukilxz @electricface

**Comment by moham96** [comment]
For some reason I can't reproduce the issue anymore, I didn't change any config file or upgraded any package.
Maybe the issue happens at random! 
one thing I noticed is that I no longer get the [checkmark](https://github.com/linuxdeepin/dde-session-ui/blob/master/widgets/img/avatar_checked%402x.png) on my first user's avatar(which I used to see when I had the issue)

Regards

**Comment by justforlxz** [comment]
Maybe the dbus of login thinks that you didn't log out, so greeter thinks that you are logged in. In fact, X has already quit, so you can't switch.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
