### ISSUE TITLE
深度系统更新候重启卡在logo处(Deepin system  is stuck at logo when updated new version and restart)

### ISSUE THREAD

**Issue by iceqing** [linuxdeepin/dde-session-ui#42]
每次更新新版本，重启都卡在logo处，具体为：重启关闭电脑时，达到的logo处没有任何提示。一致卡在这里，求助。(Each time I updated my system and restart, the PC would stuck at logo, I want to why, how to solve this problem?)

![image](https://user-images.githubusercontent.com/39587710/48746733-a5cc6a00-ecab-11e8-9c59-96653ec12526.png)

网上其他用户也遇到了类似情况（Other people have encountered this situation）：
1. [安装成功后重启卡在logo界面](https://bbs.deepin.org/forum.php?mod=viewthread&tid=144093)
2. [求助装好deepin第一个问题是无法关机，每次关机都会卡住没](http://tieba.baidu.com/f?kz=5907380665&mo_device=1&ssid=0&from=844b&uid=0&pu=usm2%2Csz320_1001%2Ctaiphone_2_8.0_24_70.0&bd_page_type=1&baiduid=52C93F95ECC4D95880D2019CDDB856EA&tj=www_normal_5_0_10_title&referer=m.baidu.com%3Fpn%3D0&red_tag=t0019677459&traceid=)
3. https://bbs.deepin.org/forum.php?mod=viewthread&tid=135933

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
