### ISSUE TITLE
lightdm-deepin-greeter - ScreenScaleFactor independent from desktop?

### ISSUE THREAD

**Issue by maurocolella** [linuxdeepin/dde-session-ui#45]
Hello,

I am on a large screen. My resolution is set to 3840x2160.

My scale factor is set to 3 to make texts more readable.

Unfortunately, this setting breaks the login screen. The login password text box then becomes so big it's clipped.

To work around the issue, I have set: `ScreenScaleFactor=2.5`

In:
`/etc/lightdm/lightdm-deepin-greeter.conf`

But every time the software updates, the setting is reset.

Is there a way to override this setting more permanently?

**Comment by felixonmars** [comment]
My gut feels that is not the right way to fix the issue. @justforlxz Please take a look at the text clipped part.

**Comment by justforlxz** [comment]
There should be no password text clipped problems now, and new fixes have been included in the updates pushed two weeks ago.

deepin-session-ui >= 4.8.6

**Comment by maurocolella** [comment]
I'll try to confirm the fix on Manjaro Linux.

**Comment by maurocolella** [comment]
I believe I can confirm the fix. I have try to set the scaling factor again to `3` from settings, logout, login, and I do not get textbox clipping.

In my `lightdm-deepin-greeter.conf`

```
[General]
ScreenScaleFactor=3
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
