### ISSUE TITLE
Security issue in dde-lock with external monitor

### ISSUE THREAD

**Issue by DionScheper** [linuxdeepin/dde-session-ui#46]
When using dde-lock to lock the screen you can hook up an external monitor and the lock screen will not resize. This allows you to use the existing session of the user and open terminals, etc. This renders the lock screen ineffective.

Tested with Thinkpad t440s running AntergOS (Arch).
Internal monitor of 1600x1200, external monitor 1920x1080.

**Comment by justforlxz** [comment]
It should now automatically adapt to the screen. version 4.8.13

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
