### ISSUE TITLE
deepin-lightdm-greeter: honor gsettings com.deepin.dde.appearance background-uris

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/dde-session-ui#48]
deepin-lightdm-greeter, or dde-session-ui, should not hard code any background path. Instead, it should query gsettings com.deepin.dde.appearance background-uris for default background image.

**Comment by justforlxz** [comment]
I will consider and verify. Thank you.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
