### ISSUE TITLE
deepin-lightdm-greeter: white screen when boot from Fedora 30 Live

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/dde-session-ui#67]
FZUG members try to build a LiveISO for Fedora 30 with DDE. But it has high probability that the LiveISO boot into a white screen at deepin-lightdm-greeter.

If type some text and push enter, the white screen is get over and user can login.

There is minor chance that the issue did not appear. So it seem a race condition during LiveOS booting.

I uploaded the iso to baidu pan:

https://pan.baidu.com/s/1F7LKfptwc_zZteMHVGLXcw 
code: 2xzv 

Every deepin package has updated to latest version except file-manager.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
