### ISSUE TITLE
Add username text field to deepin greeter

### ISSUE THREAD

**Issue by cioby23** [linuxdeepin/dde-session-ui#7]
Please add an username text field to the deepin greeter in order to allow manual login for example in the case of Active Directory authentication.
Thanks

**Comment by manateelazycat** [comment]
@cioby23 Thanks for your suggestion.

Deepin desktop environment is designed for ordinary users, when the new multi-user, you can use the mouse to select a different user login.

We will not provide a custom user login, it will log the logic to do more complex.

Anyway, thank you very much for your suggestion.
