### ISSUE TITLE
Invisible button

### ISSUE THREAD

**Issue by TiagoMRodrigues** [linuxdeepin/dde-session-ui#74]
When the computer starts and I enter on lightdm to enter the password I can switch from deepin to any other DE like i3. But when I logout from deepin the button isn't there. but if I blindly spam the place where it usually is I can enter in the select Desktop Environment menu.

**Comment by TiagoMRodrigues** [comment]
In fact is a bit more nuanced. It only happens in one of 2 screens
here is a gif. because it is low res I will say what i was doing
- Starting lightdm fresh from rebooting
- Show that the button to switch WM is there in both screens
- Enter password / login with deepin / logout from my account
- Show that only one button to switch DE is visible but i can click the invisible anyway to get into the menu
![deepin-error](https://user-images.githubusercontent.com/6720595/56021857-60641400-5d02-11e9-821e-ca44cd1402af.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
