### ISSUE TITLE
[archlinux] lightdm-deepin-greeter "can not find any monitor"

### ISSUE THREAD

**Issue by ngrande** [linuxdeepin/dde-session-ui#8]
Since today i have the problem that the lightdm-deepin-greeter is no more working for me. 
The only things that have changed since then are these two updates:

    [2016-12-09 10:29] [ALPM] upgraded deepin-desktop-schemas (3.0.11-1 -> 3.0.12-1)
    [2016-12-09 15:45] [ALPM] upgraded deepin-go-lib (0.5.1-2 -> 0.5.2-1)

jounralctl boot output:

    lightdm-deepin-greeter[786]: can not find any monitor retray in 15 second...

as a workaround i am using the lighitdm-gtk-greeter for the moment. After a successful startup and login i can start the lightdm-deepin-greeter manually and it works. 

Please tell me if i can provide more information (if so where i should look at...)

Setup information:

    Linux Xxx 4.8.12-3-ARCH #1 SMP PREEMPT Thu Dec 8 16:10:23 CET 2016 x86_64 GNU/Linux

using noveau with a nvidia graphics card

**Comment by felixonmars** [comment]
I cannot reproduce it here. Please try again with a full upgrade, as some more deepin packages were released today.

**Comment by ngrande** [comment]
yes it's working now again - did an update on monday which did the trick 👍

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
