### ISSUE TITLE
deepin-lightdm-greeter 4.9.4 startup faild in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/dde-session-ui#89]
systemd log:
![2019-04-24 10-30-30 的屏幕截图](https://user-images.githubusercontent.com/1880237/56628336-03f6e200-667c-11e9-89de-b82cfcc32c19.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
