### ISSUE TITLE
dde-offline-upgrader

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-session-ui#9]
normaly i'm use upgrade system in terminal with apt dist-upgrade

Today i'm test deepin upgrade system and i don't understand why after upgrade packages system is rebooted without ask me about this

This is danger, maybe after click in upgrade system, user working and don't save all works and system just reboot without any confirmation

I think don't need open black full screen during upgrading, maybe one pop up over all windows alerting about upgrading and block dde-shutdown to not work during upgrading

But more important, never reboot system without confirmation

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
